### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by siderakis** [dbaggett/medallion#1]
Hey, I just wanted to say this is awesome! I'm going to link to it from the Rejoiner docs.

**Comment by dbaggett** [comment]
I greatly appreciate you considering this project as a worthy Rejoiner example! I have all the services running in Kubernetes for the 🍒 on top. I plan to push this work up soon.

**Comment by siderakis** [comment]
I'm looking forward to seeing this with kubernetes!

I added a link here http://rejoiner.io/docs/examples.html#community-examples

Thanks!
